name: "🏊🏊🏊 publish"

on: 
    push: 
      branches:
        - master
    pull_request:
      types: [closed]

jobs:`
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      # - name: Run Jest
      #   uses: stefanoeb/jest-action@1.0.3
      - run: npm install
      # - run: npm ci
      - run: npm test

  publish-npm:
    needs: build
    # name: "☄️ publish"
    runs-on: ubuntu-latest
    steps:
      # - name: 💦 checkout
      - uses: actions/checkout@v2
      # - name: 🍄 node
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      # - name: 💦 publish
      # - run: npm ci
      - run: npm publish --access public
        env: 
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
      # - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

