name: "🏊🏊🏊 Publish"

on:
  push:
    branches:
      - master
  pull_request:
    types: [closed]

jobs:
  build:
    name: 🧩🧩 Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - name: 🚥 Run Jest
        run: |
          npm install 
          npm test
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}